# test compose file; override defaults with un/safe values to facilitate development

services:
  web-server:
    command: cargo watch -q -c -w /code/crates/services -w /code/crates/libs -x "test --bin=web-example"
    environment:
      - RUST_LOG=warn
    volumes:
      - ../../../../source:/code