# development compose file; override defaults with un/safe values to facilitate development

services:
  web-server:
    command: cargo watch -q -c -w /code/crates -x "run --bin=web-example"
    image: localhost/rust-axum-dev
    environment:
      - RUST_LOG=debug
    working_dir: /code
    volumes:
      - ../../../../source:/code